"""Export the LangGraph topologies as Mermaid.

Run from the repo root:

    python bot/scripts/draw_graph.py            # print to stdout
    python bot/scripts/draw_graph.py --write    # write bot/docs/*.mmd

Renders offline: Mermaid is text, so nothing is sent to mermaid.ink. View the
.mmd files with a Mermaid extension, or paste into a ```mermaid block — the
README's hand-drawn diagram is checked against this output.
"""

import argparse
import os
import pathlib
import re
import sys

# Importing the agents pulls in module-level config that expects these.
for _var in (
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "API_BASE_URL",
    "API_KEY",
    "OPENROUTER_API_KEY",
):
    os.environ.setdefault(_var, "unused-by-draw-graph")

# The bot imports as the `bot` package (see Dockerfile: COPY src/ ./bot/),
# so expose the repo root rather than bot/src.
_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT / "bot"))

from src.graph.workflow import graph, single_stock_graph  # noqa: E402

_OUT_DIR = _ROOT / "bot" / "docs"

_GRAPHS = {
    "workflow-full": graph,
    "workflow-single-stock": single_stock_graph,
}


_README = _ROOT / "README.md"

# The block in README.md tagged with _MARKER is replaced wholesale by --write.
_MARKER = "<!-- generated by bot/scripts/draw_graph.py — do not edit by hand -->"
_BLOCK_RE = re.compile(
    re.escape(_MARKER) + r"\n```mermaid\n.*?```",
    re.DOTALL,
)


def _sync_readme(mermaid: str) -> str:
    """Replace the marked block in README.md. Returns a status line."""
    text = _README.read_text()
    if not _BLOCK_RE.search(text):
        return f"! {_MARKER} not found in README.md — left alone"
    new = _BLOCK_RE.sub(f"{_MARKER}\n```mermaid\n{mermaid.rstrip()}\n```", text)
    if new == text:
        return "README.md already up to date"
    _README.write_text(new)
    return "updated README.md"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write",
        action="store_true",
        help=f"write {_OUT_DIR}/*.mmd and sync the README block",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the README block is stale (for CI)",
    )
    args = ap.parse_args()

    rendered = {n: g.get_graph().draw_mermaid() for n, g in _GRAPHS.items()}

    if args.check:
        text = _README.read_text()
        match = _BLOCK_RE.search(text)
        embedded = match.group(0).split("```mermaid\n", 1)[1] if match else ""
        if embedded.rstrip("`\n") == rendered["workflow-full"].rstrip():
            print("README.md is up to date")
            return
        raise SystemExit("README.md graph is stale — rerun with --write")

    if not args.write:
        for name, mermaid in rendered.items():
            print(f"── {name} " + "─" * (60 - len(name)))
            print(mermaid)
        return

    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, mermaid in rendered.items():
        path = _OUT_DIR / f"{name}.mmd"
        path.write_text(mermaid)
        print(f"wrote {path.relative_to(_ROOT)}")
    print(_sync_readme(rendered["workflow-full"]))


if __name__ == "__main__":
    main()
